/**
 * Auto-Generated Tags Tests
 * 
 * Tests the auto-generation rules for machine tags.
 * 
 * ROUND 81 PHASE 2: Test file per contract.
 */

import { describe, it, expect } from 'vitest';
import { 
  getAutoGeneratedTags, 
  AutoGeneratedTag 
} from '../utils/attributeGenerator';
import { PlacedModule, Connection, ModuleType } from '../types';
import { v4 as uuidv4 } from 'uuid';

// Test helper to create a simple module
function createModule(type: ModuleType, x = 0, y = 0): PlacedModule {
  const id = uuidv4();
  return {
    id,
    instanceId: id,
    type,
    x,
    y,
    rotation: 0,
    scale: 1,
    flipped: false,
    ports: [
      { id: `${type}-input-0`, type: 'input' as const, position: { x: 25, y: 50 } },
      { id: `${type}-output-0`, type: 'output' as const, position: { x: 75, y: 50 } },
    ],
  };
}

// Test helper to create a connection
function createConnection(): Connection {
  return {
    id: uuidv4(),
    sourceModuleId: uuidv4(),
    sourcePortId: 'output-0',
    targetModuleId: uuidv4(),
    targetPortId: 'input-0',
    pathData: 'M 0 0 L 100 100',
  };
}

describe('Auto-Generated Tags (D4)', () => {
  // Rule 1: Has `core-furnace` → tag: `core-source`
  describe('Rule 1: core-source tag', () => {
    it('should add core-source tag when core-furnace is present', () => {
      const modules = [createModule('core-furnace')];
      const connections: Connection[] = [];
      
      const tags = getAutoGeneratedTags(modules, connections);
      
      expect(tags).toContain('core-source');
    });

    it('should NOT add core-source tag when core-furnace is absent', () => {
      const modules = [createModule('gear')];
      const connections: Connection[] = [];
      
      const tags = getAutoGeneratedTags(modules, connections);
      
      expect(tags).not.toContain('core-source');
    });
  });

  // Rule 2: Has elemental module → tag: `elemental`
  describe('Rule 2: elemental tag', () => {
    it('should add elemental tag for fire-crystal', () => {
      const modules = [createModule('fire-crystal')];
      const connections: Connection[] = [];
      
      const tags = getAutoGeneratedTags(modules, connections);
      
      expect(tags).toContain('elemental');
    });

    it('should add elemental tag for lightning-conductor', () => {
      const modules = [createModule('lightning-conductor')];
      const connections: Connection[] = [];
      
      const tags = getAutoGeneratedTags(modules, connections);
      
      expect(tags).toContain('elemental');
    });

    it('should add elemental tag for amplifier-crystal', () => {
      const modules = [createModule('amplifier-crystal')];
      const connections: Connection[] = [];
      
      const tags = getAutoGeneratedTags(modules, connections);
      
      expect(tags).toContain('elemental');
    });

    it('should NOT add elemental tag for non-elemental modules', () => {
      const modules = [createModule('gear'), createModule('core-furnace')];
      const connections: Connection[] = [];
      
      const tags = getAutoGeneratedTags(modules, connections);
      
      expect(tags).not.toContain('elemental');
    });
  });

  // Rule 3: Has rare module → tag: `advanced-tech`
  describe('Rule 3: advanced-tech tag', () => {
    it('should add advanced-tech tag for temporal-distorter', () => {
      const modules = [createModule('temporal-distorter')];
      const connections: Connection[] = [];
      
      const tags = getAutoGeneratedTags(modules, connections);
      
      expect(tags).toContain('advanced-tech');
    });

    it('should add advanced-tech tag for ether-infusion-chamber', () => {
      const modules = [createModule('ether-infusion-chamber')];
      const connections: Connection[] = [];
      
      const tags = getAutoGeneratedTags(modules, connections);
      
      expect(tags).toContain('advanced-tech');
    });

    it('should add advanced-tech tag for arcane-matrix-grid', () => {
      const modules = [createModule('arcane-matrix-grid')];
      const connections: Connection[] = [];
      
      const tags = getAutoGeneratedTags(modules, connections);
      
      expect(tags).toContain('advanced-tech');
    });

    it('should NOT add advanced-tech tag for non-rare modules', () => {
      const modules = [createModule('gear'), createModule('rune-node')];
      const connections: Connection[] = [];
      
      const tags = getAutoGeneratedTags(modules, connections);
      
      expect(tags).not.toContain('advanced-tech');
    });
  });

  // Rule 4: Has ≥5 connections → tag: `highly-connected`
  describe('Rule 4: highly-connected tag', () => {
    it('should add highly-connected tag for 5 connections', () => {
      const modules = [createModule('gear'), createModule('gear')];
      const connections = Array(5).fill(null).map(() => createConnection());
      
      const tags = getAutoGeneratedTags(modules, connections);
      
      expect(tags).toContain('highly-connected');
    });

    it('should add highly-connected tag for more than 5 connections', () => {
      const modules = [createModule('gear'), createModule('gear')];
      const connections = Array(10).fill(null).map(() => createConnection());
      
      const tags = getAutoGeneratedTags(modules, connections);
      
      expect(tags).toContain('highly-connected');
    });

    it('should NOT add highly-connected tag for less than 5 connections', () => {
      const modules = [createModule('gear'), createModule('gear')];
      const connections = [createConnection(), createConnection(), createConnection()];
      
      const tags = getAutoGeneratedTags(modules, connections);
      
      expect(tags).not.toContain('highly-connected');
    });
  });

  // Rule 5: Connection density > 2.5 → tag: `dense-circuit`
  describe('Rule 5: dense-circuit tag', () => {
    it('should add dense-circuit tag when density > 2.5', () => {
      // 4 modules with 11 connections = density 2.75
      const modules = [
        createModule('gear', 0, 0),
        createModule('gear', 100, 0),
        createModule('gear', 200, 0),
        createModule('gear', 300, 0),
      ];
      const connections = Array(11).fill(null).map(() => createConnection());
      
      const tags = getAutoGeneratedTags(modules, connections);
      
      expect(tags).toContain('dense-circuit');
    });

    it('should NOT add dense-circuit tag when density <= 2.5', () => {
      // 4 modules with 10 connections = density 2.5 (not greater than)
      const modules = [
        createModule('gear', 0, 0),
        createModule('gear', 100, 0),
        createModule('gear', 200, 0),
        createModule('gear', 300, 0),
      ];
      const connections = Array(10).fill(null).map(() => createConnection());
      
      const tags = getAutoGeneratedTags(modules, connections);
      
      expect(tags).not.toContain('dense-circuit');
    });
  });

  // Rule 7: Has rune-node OR phase-modulator → tag: `arcane-enhanced`
  describe('Rule 7: arcane-enhanced tag', () => {
    it('should add arcane-enhanced tag for rune-node', () => {
      const modules = [createModule('rune-node')];
      const connections: Connection[] = [];
      
      const tags = getAutoGeneratedTags(modules, connections);
      
      expect(tags).toContain('arcane-enhanced');
    });

    it('should add arcane-enhanced tag for phase-modulator', () => {
      const modules = [createModule('phase-modulator')];
      const connections: Connection[] = [];
      
      const tags = getAutoGeneratedTags(modules, connections);
      
      expect(tags).toContain('arcane-enhanced');
    });

    it('should add arcane-enhanced tag for both rune-node and phase-modulator', () => {
      const modules = [createModule('rune-node'), createModule('phase-modulator')];
      const connections: Connection[] = [];
      
      const tags = getAutoGeneratedTags(modules, connections);
      
      expect(tags).toContain('arcane-enhanced');
    });

    it('should NOT add arcane-enhanced tag for other modules', () => {
      const modules = [createModule('gear'), createModule('core-furnace')];
      const connections: Connection[] = [];
      
      const tags = getAutoGeneratedTags(modules, connections);
      
      expect(tags).not.toContain('arcane-enhanced');
    });
  });

  // Rule 6 (existing): Has shield-shell → tag: `protective`
  describe('Rule 6: protective tag (existing)', () => {
    it('should have protective tag through module tags (not auto-generated)', () => {
      // Note: protective is added through MODULE_TAG_MAP, not auto-generation
      // This test verifies the existing behavior is preserved
      const modules = [createModule('shield-shell')];
      const connections: Connection[] = [];
      
      // Auto-generated tags don't include 'protective' - it's from module tags
      const tags = getAutoGeneratedTags(modules, connections);
      
      // protective is NOT in the auto-generated tags list
      // It's added through the base generateTags function
      expect(Array.isArray(tags)).toBe(true);
    });
  });

  // Combined rules tests
  describe('Combined rules', () => {
    it('should apply multiple rules simultaneously', () => {
      // Has core-furnace (core-source) + fire-crystal (elemental) + 5+ connections (highly-connected)
      const modules = [
        createModule('core-furnace'),
        createModule('fire-crystal'),
      ];
      const connections = Array(5).fill(null).map(() => createConnection());
      
      const tags = getAutoGeneratedTags(modules, connections);
      
      expect(tags).toContain('core-source');
      expect(tags).toContain('elemental');
      expect(tags).toContain('highly-connected');
    });

    it('should handle machine with all tag conditions', () => {
      const modules = [
        createModule('core-furnace'),      // core-source
        createModule('fire-crystal'),      // elemental
        createModule('temporal-distorter'), // advanced-tech
        createModule('rune-node'),         // arcane-enhanced
      ];
      const connections = Array(12).fill(null).map(() => createConnection()); // density > 2.5
      
      const tags = getAutoGeneratedTags(modules, connections);
      
      expect(tags).toContain('core-source');
      expect(tags).toContain('elemental');
      expect(tags).toContain('advanced-tech');
      expect(tags).toContain('arcane-enhanced');
      expect(tags).toContain('dense-circuit');
      expect(tags).toContain('highly-connected');
    });
  });
});
